# Generated by Django 5.0.2 on 2024-02-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='static')),
                ('product_model', models.CharField(max_length=90)),
                ('product_spec1', models.CharField(max_length=100)),
                ('product_spec2', models.CharField(max_length=100)),
                ('product_spec3', models.CharField(max_length=100)),
                ('product_amount', models.IntegerField()),
            ],
        ),
    ]
