# Generated by Django 5.0.2 on 2024-02-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_alter_hp_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='C:/Users/Asus/PycharmProjects/pythonProject37/static/Asus_images/')),
                ('product_model', models.CharField(max_length=90)),
                ('product_spec1', models.CharField(max_length=100)),
                ('product_spec2', models.CharField(max_length=100)),
                ('product_spec3', models.CharField(max_length=100)),
                ('product_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='C:/Users/Asus/PycharmProjects/pythonProject37/static/Dell_images/')),
                ('product_model', models.CharField(max_length=90)),
                ('product_spec1', models.CharField(max_length=100)),
                ('product_spec2', models.CharField(max_length=100)),
                ('product_spec3', models.CharField(max_length=100)),
                ('product_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lenovo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='C:/Users/Asus/PycharmProjects/pythonProject37/static/Lenovo_images')),
                ('product_model', models.CharField(max_length=90)),
                ('product_spec1', models.CharField(max_length=100)),
                ('product_spec2', models.CharField(max_length=100)),
                ('product_spec3', models.CharField(max_length=100)),
                ('product_amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='hp',
            name='product_image',
            field=models.ImageField(upload_to='C:/Users/Asus/PycharmProjects/pythonProject37/static/Hp_images/'),
        ),
    ]
