# Generated by Django 5.0.2 on 2024-02-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0004_customer_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_product', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('mob_no1', models.IntegerField(max_length=10)),
                ('mob_no2', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
