# Generated by Django 5.0.2 on 2024-02-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0005_customerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customerinfo',
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='mob_no1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='mob_no2',
            field=models.IntegerField(),
        ),
    ]
